### ISSUE TITLE
Presets missing in package

### ISSUE THREAD

**Issue by JulianDMartinez** [metasidd/Orb#1]
The presets mentioned in the ReadMe seem to be missing in the package. 

Suggest placing `OrbConfiguration` in a dedicated `OrbConfiguration.swift` file.

**Comment by metasidd** [comment]
Created a separate configuration file in ab531882bbfe8a36c510a10d4ceec1df0bf1dccc.

**Comment by metasidd** [comment]
I don't think we should add the presets to the file her. Given the number of attributes, this seems like something devs can modify as they need from the documentation.

**Comment by JulianDMartinez** [comment]
Makes sense! Maybe we can clarify the documentation to indicate so? 

It currently says that they are included in the package.

Could be in the lines of:

**Preset Configurations**

Explore these beautiful example configurations to see what you can achieve with OrbConfiguration. Copy any of the presets below to use in your own project, and feel free to customize them to match your vision.

**Comment by metasidd** [comment]
👍 Fixed. b5cfa069132dc0e4c7033eff68a72f74cc84cc43
