### ISSUE TITLE
Placeholder name left in licensing in ReadMe

### ISSUE THREAD

**Issue by JulianDMartinez** [metasidd/Orb#2]
I noticed that the licensing part in the ReadMe section has a placeholder for the name. Did you intend this?

Suggest placing a licensing badge at the top of the ReadMe: ![MIT License](https://img.shields.io/badge/license-MIT-blue.svg)

Suggest adding as a LICENSE file to the repo, this way it readily shows in "About":
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

**Comment by metasidd** [comment]
Addressed in fd14d495dd26dd4d371081c373286761201d1f31, and 87096ec7462e09edea555b1215291a70c5e1de34. Thanks!
